I Experiment name  : reversal_learning_6_pokes
I Task name : reversal_learning_6_pokes
I Subject ID : m482
I Start date : 2018/04/06 17:29:27

S {'sound_a_reward': 5, 'poke_b_reward': 4, 'period_before_iti': 10, 'b_forced_state': 13, 'choice_state': 2, 'start_state': 14, 'a_forced_state': 12, 'inter_trial_interval': 9, 'init_trial': 1, 'poke_a_reward': 3, 'sound_b_no_reward': 8, 'free_reward_trial': 11, 'sound_b_reward': 6, 'sound_a_no_reward': 7}

E {'new_task': 30, 'poke_2': 16, 'poke_1': 15, 'poke_1_out': 21, 'poke_6': 20, 'old_task': 29, 'poke_5_out': 25, 'poke_5': 19, 'poke_4': 18, 'poke_3': 17, 'poke_4_out': 24, 'poke_2_out': 22, 'poke_3_out': 23, 'poke_6_out': 26, 'reward_consumption_timer': 28, 'session_timer': 27}

D 0 14
D 5 11
P 6 FR#2
D 349 17
D 646 23
D 999 19
D 1000 6
D 1250 4
D 1302 10
D 3102 25
D 3108 19
D 3138 25
D 3389 9
D 5139 11
P 5140 FR#1
D 21326 20
D 21327 5
D 21577 3
D 21629 10
D 25628 26
D 25879 9
D 26296 20
D 26385 26
D 26401 20
D 26419 26
D 27001 20
D 27198 26
D 27629 1
D 27753 20
D 27775 26
D 28201 20
D 28248 26
D 28636 20
D 28778 26
D 30038 20
D 30334 26
D 30375 20
D 30413 26
D 30988 20
D 31104 26
D 31469 17
D 31470 2
D 31557 23
D 31935 19
D 31935 6
D 32186 4
D 32238 10
D 36039 25
D 36089 19
D 36656 25
D 36906 9
P 36909 T#:1, R#:3, B#:0, S:0, C:0, O:1, Cave:0.559, Count:0, Poke_IAB: 365,RP:{'good': 0.9, 'bad': 0.1}, FT:0
D 38300 19
D 38355 25
! Error during framework run.
! Traceback (most recent call last):
!   File "<stdin>", line 1, in <module>
!   File "pyControl/framework.py", line 267, in run
!   File "pyControl/framework.py", line 232, in _update
!   File "pyControl/state_machine.py", line 130, in _process_timed_goto_state
!   File "pyControl/state_machine.py", line 58, in goto_state
! pyControlError: Invalid state name passed to goto_state: NoneV n_rewards: 3
V n_trials: 1
V block_number: 0
V cumulative_reversals: 0
